
// timestamp server
export const GET_COMPILATION_DATA = 'GET_COMPILATION_DATA'
export const GET_TIMESTAMP_DATA = 'GET_TIMESTAMP_DATA'
export const GET_EPISODE_DATA = 'GET_EPISODE_DATA'
export const GET_CHARACTER_DATA = 'GET_CHARACTER_DATA'
export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA'

//video server 
export const GET_LINKED_VIDEOS = "GET_LINKED_VIDEOS"
export const GET_UNLINKED_VIDEOS = "GET_UNLINKED_VIDEOS"
export const GET_LINK_TO_EPISODE = "GET_LINK_TO_EPISODE"
export const RESET_LINK_TO_EPISODE = "RESET_LINK_TO_EPISODE"

// authenticate actions
export const GET_LOCAL_AUTH_TOKEN = "GET_LOCAL_AUTH_TOKEN"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_REQUEST_STATUS = "LOGIN_REQUEST_STATUS"
export const LOGOUT = "LOGOUT"

// api - notifications
export const API_NEW_REQUEST = "API_NEW_REQUEST"
export const API_REQUEST_ERROR = "API_REQUEST_ERROR"
export const CLEAR_ALL_ERRORS = "CLEAR_ALL_ERRORS"
export const SUCSESS_INFO = "SUCSESS_INFO"
export const RESET_SUCSESS_INFO = "RESET_SUCSESS_INFO"